name: Check if notebook is executable and linted

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: ${{ github.head_ref }}/requirements.txt
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "${{ github.head_ref }}/task.ipynb"
        params: "PATHTOPARAMS.json"
        isReport: False
        poll: True
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: "${{ github.head_ref }}_notebook"
        path: ${{ RUNNER.temp }}/nb-runner
    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
        RUNNER: ${{ toJson(runner) }}
      # Deploy job
  deploy:
    needs: run
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: "${{ github.head_ref }}_notebook"
