name: Check notebook

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: danilkladnitsky/auto-nlp-action@v0.0.1-alpha
      with:
        home-task-filename: notebook.ipynb

    