name: Check if notebook is executable and linted

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: ${{ github.head_ref }}/requirements.txt
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "${{ github.head_ref }}/task.ipynb"
        params: "PATHTOPARAMS.json"
        isReport: False
        poll: True
    - name: Tar files
      run: |
        cd ${{ RUNNER.temp }}/nb-runner/
        mkdir _site
        mv task.html _site/task.html
        tar -cvf artifact.tar _site/
        unlink artifact.tar
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: github-pages
        path: ${{ RUNNER.temp }}/nb-runner/artifact.tar
    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
        RUNNER: ${{ toJson(runner) }}

  deploy:
    needs: run
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ RUNNER.temp }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2